### ISSUE TITLE
Index with unexpected dtype  datetime64[ns, tzfile('Zulu')]

### ISSUE THREAD

**Issue by BarrancoC** [man-group/arctic#479]
#### Arctic Version

```
# 1.49.0
```

#### Arctic Store

```
# TickStoreV3
```

#### Description of problem and/or code sample that reproduces the issue

Libraries seems to have index type datetime64[ns, tzfile('Zulu')]
This seems to prevent some basic functions to work.

Example:

import pytz
data = pd.DataFrame([
('2017-07-28 23:59:59',40),
('2017-07-29 23:59:59',41),
('2017-07-30 23:59:59',42)
],columns=['timestamp','data'])
data.index = data['timestamp'].apply(lambda x: pd.Timestamp(x, tz=pytz.UTC))
data = data.drop(axis=1, labels=['timestamp'])
store.delete_library('user.test_library')
store.initialize_library('user.test_library', lib_type='TickStoreV3')
lib = store.get_library('user.test_library')
symbol=''
lib.write(symbol,data)
df = lib.read('')
df.index # datetime64[ns, tzfile('Zulu')]
data.index # datetime64[ns, UTC]

In this example, data.plot() would work, while df.plot() would give error
AttributeError: 'tzfile' object has no attribute '_transition_info'

Can someone please explain what is going on and how can I prevent this from happening to new libraries?

**Comment by bmoscon** [comment]
what OS are you using?

**Comment by BarrancoC** [comment]
Hi! I'm using Windows7

**Comment by bmoscon** [comment]
This is a problem with tzfile (which I believe comes from python-dateutil) and I believe is Windows related as I cannot reproduce on Linux.

**Comment by bmoscon** [comment]
Looks like this is a problem with pandas:

https://stackoverflow.com/questions/28539093/error-when-plotting-a-pandas-timeseries-if-dates-have-timezones

https://github.com/pandas-dev/pandas/issues/2683

It looks like the way you are adding timezones to the dataframe is causing the issues. Its weird though because i dont have any issues on linux so i wonder if its a windows issue (windows + python + timezones has always been problematic for me)

**Comment by BarrancoC** [comment]
Yes, plot() seems to work only with UTC, and for some reason Arctic assigns timezone "Zulu" to the index. At least on windows.

**Comment by bmoscon** [comment]
Zulu means GMT time I believe, so unless that is your local time, I suspect there is a problem somewhere with a timezone library

**Comment by BarrancoC** [comment]
Zulu should be the same of UTC, but still is a different timezone, resulting in a different dtype for the index. 
The problem could be avoided by changing the index back to UTC after extracting data from the library, still is pretty annoying that this unwanted edit can't be avoided.

**Comment by BarrancoC** [comment]
So far I've been running code from a Jupyter  notebook.
If I try to run the same code from the unix terminal (using ipython)  I have a slightly different result:

```
In [3]: import pytz
   ...: data = pd.DataFrame([
   ...: ('2017-07-28 23:59:59',40),
   ...: ('2017-07-29 23:59:59',41),
   ...: ('2017-07-30 23:59:59',42)
   ...: ],columns=['timestamp','data'])
   ...: data.index = data['timestamp'].apply(lambda x: pd.Timestamp(x, tz=pytz.UTC))
   ...: data = data.drop(axis=1, labels=['timestamp'])
   ...: store.delete_library('user.test_library')
   ...: store.initialize_library('user.test_library', lib_type='TickStoreV3')
   ...: lib = store.get_library('user.test_library')
   ...: symbol=''
   ...: lib.write(symbol,data)
   ...: df = lib.read('')
   ...:

In [4]: df.index
Out[4]:
DatetimeIndex(['2017-07-28 23:59:59+00:00', '2017-07-29 23:59:59+00:00',
               '2017-07-30 23:59:59+00:00'],
              dtype='datetime64[ns, tzfile('/usr/share/zoneinfo/Etc/UTC')]', freq=None)

In [5]: data.index
Out[5]:
DatetimeIndex(['2017-07-28 23:59:59+00:00', '2017-07-29 23:59:59+00:00',
               '2017-07-30 23:59:59+00:00'],
              dtype='datetime64[ns, UTC]', name='timestamp', freq=None)

```

Instead of explicitly obtain tz Zulu I obtain 
dtype='datetime64[ns, tzfile('/usr/share/zoneinfo/Etc/UTC')]', freq=None)

Could it be that the notebook is pointing to the wrong file in /usr/share/zoneinfo/Etc ?

**Comment by bmoscon** [comment]
could be. I'm no jupyter expert, but some quick googling turns up some tidbits that make it look like jupyter could be to blame:

http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/execute_time/readme.html#timezones

**Comment by jasonlocal** [comment]
Jupyter Notebook related legacy issue
