### ISSUE TITLE
Arctic Debug connection problems

### ISSUE THREAD

**Issue by yschimke** [man-group/arctic#633]
Ideally when connecting to a named service with multiple backend servers, it would be good to be able to do a health check of the individual hosts.

e.g. research -> mongodb://0.myserver.com + mongodb://1.myserver.com

Then open connections to each one in turn and validate with the simplest possible query

**Comment by bmoscon** [comment]
that seems more of a mongo thing than arctic thing

**Comment by yschimke** [comment]
@bmoscon it would be ideal if it's implemented via some simple mongo call, but as we replace direct client usage of mongo APIs, it would be ideal if there was a quick debug tool to health check your cluster when diagnosing production issues.

**Comment by yschimke** [comment]
@shashank88 yes - but not just an int.  Ideally it would be one python line that returned a data structure with enough information for us to investigate issues with Arctic clusters.  The goal is users capturing enough information to diagnose most problems when there is a time or network gap to the person doing support.

- which hosts are behind this named cluster
- can we ping each of them + latency
- can we connect
- can we query with the mongo equivelant of "select 1 from dual"
- can we run an Arctic query on the collection

I'm over designing it here, but a way to capture the health of an Arctic cluster at this point in time as observed from the reporters host.

**Comment by shashank88** [comment]
This is something I started integrating in the arctic-explorer but using mongo directly, since I think it makes more sense to have this in a self-service tool than a library for data access. Should we add the code in arctic or just close this for now? @yschimke

**Comment by yschimke** [comment]
You can close, but I don't think it can be solely in a standalone admin tool.  It does need to run on a users machine etc with the versions of libraries they have etc.

**Comment by jasonlocal** [comment]
Resolved bt running on user machine
