### ISSUE TITLE
Per library version requirements

### ISSUE THREAD

**Issue by yschimke** [man-group/arctic#652]
Suggested feature:

READ_VERSION_MIN and WRITE_VERSION_MIN for the library

**Comment by yschimke** [comment]
Wanted to allow us to fail fast if clients would rad the wrong data if they don't support a new feature, or corrupt other clients if they write in new formats.  Can be used by disable/hybrid/enabled flags to migrate libraries through different python spec formats.

**Comment by dimosped** [comment]
In order to implement this we need to add version information in the arctic module.
Please check:
https://github.com/manahl/arctic/pull/654

**Comment by jasonlocal** [comment]
Issue is covered in #654
