### ISSUE TITLE
Please add support of Dask for chunk store

### ISSUE THREAD

**Issue by javy-kong** [man-group/arctic#807]
Dask is very useful in many scenarios. If chunkstore can provide an interface to allow data loading directly into Dask, it would be extremely useful.

**Comment by shashank88** [comment]
I am only slightly familiar with Dask, but can't you convert a Dask df to pandas and then use Arctic as before? Also, a Dask df doesn't have to reside in one node which would be interesting on how to handle wrt storing in Mongo

**Comment by shashank88** [comment]
Can you give some more details on how do you want to use ChunkStore with Dask?

**Comment by jasonlocal** [comment]
Legacy issue, more details are required- close the ticket for now.  Please feel free to reopen if Dask integration is still desired
