### ISSUE TITLE
Fix build broken due to group name change

### ISSUE THREAD

**Issue by shashank88** [man-group/arctic#828]
The group name was changed from manahl -> man-group and that seems to have broken the travis build. Probably needs a tweak in the settings somewhere

**Comment by bmoscon** [comment]
I added the correct link to the readme - so this should probably just be closed? or does something else need to change?

**Comment by shashank88** [comment]
Yeah, I had the same change locally, but I was thinking about checking if the org and org email etc also had to change. We can close this though
