### ISSUE TITLE
Question:  Reading ChunckedStore document into C# object

### ISSUE THREAD

**Issue by afriedma** [man-group/arctic#839]
#### Arctic Version

# 1.79.3
```

#### Arctic Store

```
ChunkStore
```

#### Platform and version

Windows 10

#### Description of problem and/or code sample that reproduces the issue

I am using ChunckStore with PassthroughChunker as below
lib.write(symbol, df, chunker=PassthroughChunker())

Is it possible to read contents of the "d" element into a C# object?  I don't need it to look like a dataframe per say, I just want the data to make sense after conversion.

Any help would be very appreciated.

**Comment by bmoscon** [comment]
I dont know anything about C# but if you serialize the object yourself into something like json or a a bytes blob then you should have no issue writing it to  arctic.

**Comment by afriedma** [comment]
@bmoscon Thank you for reply.

My understanding was, that you could only store pandas dataframes.  Do you have an example of what you are referring to?

**Comment by bmoscon** [comment]
check out this repo:

https://github.com/man-group/NArctic
