### ISSUE TITLE
pandas.Series.from_array got deprecated

### ISSUE THREAD

**Issue by likeapig233** [man-group/arctic#844]
#### Arctic Version

```
# 1.79.3
```

#### Platform and version

pandas = 1.0.1

#### Description of problem and/or code sample that reproduces the issue

pandas.Series.from_array has been deprecated. ..\arctic\serialization\numpy_records.py is still referring to this function, which will break the process.

Many thanks.

**Comment by shashank88** [comment]
Can you send a backward-compatible PR for this? I can get to it this weekend if you can't

**Comment by dbrakenhoff** [comment]
Any chance PR #841 will be merged soon to fix this? I'd like to start using Pandas 1.0.1 :)

**Comment by bmoscon** [comment]
fixed

**Comment by ehiggs** [comment]
Any ETA on when this will be released to [PyPI](https://pypi.org/project/arctic/#history)?
