### ISSUE TITLE
Collection file size with Mongo's WiredTiger storage engine

### ISSUE THREAD

**Issue by rajnish2704** [man-group/arctic#847]
#### Arctic Version

```
# Version: 1.79.2
```

#### Arctic Store

```
# ChunkStore
```

#### Platform and version

Ubuntu 17.10

#### Description of problem and/or code sample that reproduces the issue
We are using MongoDB version 4.2.2 with the WiredTiger storage engine. We have a collection with size 1.1 TB. The db files that we observe have a collection file with the same size with a '.wt' extension. 
The read speeds have fallen drastically upto 1/8th of the original speeds when the data was 500 GB and storage engine MMap. My query is that; if chunks are being maintained and their indices are also produced then why does the speed scale so poorly. Is there a reasonable explanation for the same? Further is there something that can be done so that we maintain the original read speeds?

**Comment by shashank88** [comment]
I think this is more a Mongo than an Arctic question. From what I understand you have changed the db engine and doubled the data size (which might or might not scale linearly). The hardware / OS / Memory sizes etc. are so many variants that it's hard to answer this in isolation. It might be worth posting in a Mongo forum.
