### ISSUE TITLE
How to change config options?

### ISSUE THREAD

**Issue by RoyalGoose** [man-group/arctic#850]
#### Arctic Version
1.79.3
#### Platform and version
Pycharm
#### Description of problem and/or code sample that reproduces the issue
How to turn off all compressions in arctic? In manual i read this strings "export DISABLE_PARALLEL=1" and "export LZ4_HIGH_COMPRESSION=1", but i dont understand where this strings i need to paste?

**Comment by shashank88** [comment]
You can paste this in the shell where you are running the script from.

**Comment by RoyalGoose** [comment]
> You can paste this in the shell where you are running the script from.

you mean in main.py where i import arcrtic?

**Comment by shashank88** [comment]
Are you on a Linux /mac? The export is a shell statement which you can paste in the terminal / item where you run your script from. eg. the shell where you do: "python main.py". iirc you can also set this from the code as well by importing the relevant variable by "from arctic._config import LZ4_HIGH_COMPRESSION" and then set it to true right at the top. The env method would be nicer though.

**Comment by RoyalGoose** [comment]
I develop my project in pycharm on windows, artic library imported in main.py. All in all i need to turn off all compression because i want to see my data in MongoDB compass without all encrypting

**Comment by bmoscon** [comment]
@RoyalGoose turning off compression won't help - the data is stored serialized so its just going to look like binary data. If you still want to do this, google "set environment variables windows" and there are a lot of articles that explain how to set these variables in windows environments.

**Comment by RoyalGoose** [comment]
> @RoyalGoose turning off compression won't help - the data is stored serialized so its just going to look like binary data. If you still want to do this, google "set environment variables windows" and there are a lot of articles that explain how to set these variables in windows environments.

ok, after this i have next question. How can i read information, which i sended to mongodb via arctik, with C++ or C#? Maybe any API or protocol or c# version of arctik?

**Comment by shashank88** [comment]
It's not going to be a trivial change but you could replicate the python protocol in C++ and read directly from mongo using the C++ SDK. Generally, it's unpleasant to work with dataframe like objects in C++ so it's not a common use case. 
Closing for now, please reopen if you have more questions
