### ISSUE TITLE
Not able to establish a connection with AWS and Arctic

### ISSUE THREAD

**Issue by rohankumar10** [man-group/arctic#857]
#### Arctic Version

```
# Arctic version here

```

#### Arctic Store

```
# VersionStore, TickStore, or ChunkStore
```

#### Platform and version

Put here
Tickstore 

#### Description of problem and/or code sample that reproduces the issue

Put Here

I am not able to establish a connection to arctic, this is the error I am getting
We are establishing a coonection with arctic using AWS.
Didnt get this error before been using this way to connect for over 6 months, this error has creeped up in the last 2 days

ServerSelectionTimeoutError               Traceback (most recent call last)
<ipython-input-3-1d3cf669b3ea> in <module>()
  
     15 ARCTIC_NAME='nutella'
---> 16 store.initialize_library(ARCTIC_NAME, lib_type=TICK_STORE)
     17 library = store[ARCTIC_NAME]
     18 symbols=library.list_symbols()

12 frames
/usr/local/lib/python3.6/dist-packages/pymongo/topology.py in _select_servers_loop(self, selector, timeout, address)
    207             if timeout == 0 or now > end_time:
    208                 raise ServerSelectionTimeoutError(
--> 209                     self._error_message(selector))
    210 
    211             self._ensure_opened()

ServerSelectionTimeoutError:#: [Errno 111] Connection refused

**Comment by rohankumar10** [comment]
@sreenumalae

**Comment by rohankumar10** [comment]
@rob256 @bmoscon Can you help me out here?

**Comment by rob256** [comment]
It looks like either your mongos/mongod isn't running on port 27017, or your port on AWS is not open. First try doing a `curl ec2-3-134-84-140.us-east-2.compute.amazonaws.com:27017` to ensure you can access your mongo node, or likewise opening up `http://ec2-3-134-84-140.us-east-2.compute.amazonaws.com:27017` in your browser.

**Comment by bmoscon** [comment]
I agree with the above, it sounds like an AWS issue, not an arctic issue, especially if it was working for months then suddenly stopped working.

**Comment by rohankumar10** [comment]
Alright, will check that out and update you guys!

**Comment by rohankumar10** [comment]
Thanks @bmoscon and @rob256 It was AWS issue. Thanks for your help
