### ISSUE TITLE
Arctic TickStore Speed 

### ISSUE THREAD

**Issue by gausscapital** [man-group/arctic#862]
#### Arctic Version

```
# Arctic version here
```

#### Arctic Store

```
# TickStore
```

#### Windows

I have a time series that contains all trades in Bitcoin in the Bitfinex exchange since 2013, the current size of the time series is 90.335.052 rows × 4 columns. 
I had the database in a csv file and i uploaded into arctic using the following code :
```
dbstore = Arctic('localhost')
dbstore.initialize_library('BITFINEX_TRADE', lib_type=TICK_STORE)
lib = dbstore['BITFINEX_TRADE']
lib.write('tBTCUSD', ts,
                      metadata={'Source': 'BITIFINEX', 'Ticker': 'tBTCUSD', 'Type': 'Trade'})
```
for comparison i created the exact same timeseries in HDF5.

I read the arctic timeseries using the code:
```
dd = date.DateRange(start=lib.min_date('tBTCUSD'), end=lib.max_date('tBTCUSD'))
ts = lib.read('tBTCUSD', date_range=dd)
```
To read the entire timeseries took Wall time: 1min 54s in HDF5 and Wall time: 30min 23s in TICKSTORE (bellow)
![arctic](https://user-images.githubusercontent.com/63561015/84644890-14ad8b80-af00-11ea-9d3b-9c512325cb96.PNG)

From what i read of related topics the performance is not as expected, so i imagine i am not doing something right the way i store the data in arctic. (Both databases are stored on the same SSD hard drive locally on my computer)

Any guidance here ?

**Comment by pablojim** [comment]
If you are not streaming the data, I'd suggest trying to use the VersionStore rather than TickStore.

**Comment by gausscapital** [comment]
> If you are not streaming the data, I'd suggest trying to use the VersionStore rather than TickStore.

Did it, performed much better.

![VERSION_STORE](https://user-images.githubusercontent.com/63561015/84792408-18bad580-aff4-11ea-930a-654ab8342ba7.PNG)

Just out of curiosity, i thought TICK_STORE would be the recommend library type  for trade data, what is the recommended use for TICK_STORE then ?

**Comment by jamesblackburn** [comment]
TickStore is indeed meant for tick data, but perhaps there's an issue in how the data is being written - the log-line: 
         `TimeSeries data is out of order, sorting` 
indicates that the data doesn't appear to be monotonic which is causing a sort on read. So perhaps the data chunks are overlapping or similar? 

Also ensure that you're writing 'enough' data with each write() call. You want to be aiming for up to 100k rows per write if you can, as TickStore write is quite primitive and just writes a chunk into Mongo for the data you pass into it. We have a Java client which does the writing to tickstore, so it's fair to say that the Python write-path gets less use for TickStore than the read path.

**Comment by gausscapital** [comment]
Thanks @jamesblackburn thanks for the response.
In relation to chunk_size since i did an initial write() call with the entire initial data set of 90.335.052 rows, so the chunck was at maximum size for the entire time series. 
But looking at the data i see that what might be happening is that are trades that happens at the exact same time (you can see on my last screenshot an example at 2020-06-16 08:22:49.328), do you think this situation might be triggering the sort on read ?
I will run a test by pre-sorting the datetime index on the dataframe before calling the write() to a TickStore library to see if i get improvemnts on performance.
