### ISSUE TITLE
VersionStore slicing doesn't seem work.

### ISSUE THREAD

**Issue by zechzhao** [man-group/arctic#863]
#### Arctic Version

```
latest version ( downloaded yesterday)
```

#### Arctic Store

```
VersionStore
```

#### Platform and version
```
Ubuntu 19.10
MongoDB shell version v3.6.8
Python 3.7.5
```
#### Description of problem and/or code sample that reproduces the issue

The database works for me just as the quickstart example. However, when attempt the library, read slicing options, it seems does not work: as long slicing options are enabled, whether column or dateRange, the data returned is a wrong DataFrame.
e.g. 

`item = library.read('test', colums='high' ).data`  returns the full table instead of pandas.Series test.high
`item = library.read('test', date_range=DateRange(pd.to_datetime('2016-01-02'), pd.to_datetime('2016-02-03'))).data` returns an empty DataFrame.

The index of dataFrame used to write to the database and read from the database with simply `library.read('test').data` are both of the type `pandas.timestamps (datetime64)`.

Upon checking the source: the daterange in put can be `int`, `str` or `datetime.datetime`, all of them were attempted however, none of them worked. 

Not sure if there is anything else that I have missed before slicing can finally work. 

Thanks

**Comment by bmoscon** [comment]
versionstore doesnt support reading out specific columns (what you are calling slicing)

**Comment by zechzhao** [comment]
Thanks for the clarification. Any suggestions on what could I check on reading out data with in a period? thanks

**Comment by jasonlocal** [comment]
The best practice is to use ChunkStore fro reading out data for a specific period. I am going to close the issue, but please feel free to reopen if this is still an issue

**Comment by jasonlocal** [comment]
closed legacy issue
