### ISSUE TITLE
removing libraries

### ISSUE THREAD

**Issue by markm00001** [man-group/arctic#864]
#### Arctic Version

```
latest

#### Arctic Store

```
VersionStore
```

#### Platform and version

Ubuntu 18.04

#### Description of problem and/or code sample that reproduces the issue
I have just (re)installed arctic and am playing around with new libraries before using in production. One thing I cannot find in docs is how, if at all possible, I can remove existing libraries from the DB. Any help is appreciated!

**Comment by rob256** [comment]
Hi markm00001,

There is an `arctic_delete_library` console script which is available:
https://github.com/man-group/arctic/blob/master/arctic/scripts/arctic_delete_library.py

Is this what you were looking for?

If you were looking to remove every single library, then a mixture of the code from arctic_delete_library and arctic_list_libraries should achieve your desired outcome.

Thanks,
Robert

**Comment by markm00001** [comment]
Hi Robert,

This is enormously helpful. Thank you! Somehow, embarassingly, the 'delete_library' call passed me by...;)
