### ISSUE TITLE
Delete individual versions with Version Store

### ISSUE THREAD

**Issue by tomnewg** [man-group/arctic#866]
Hi guys,

is it possible to delete individual versions with Version Store? Looking into the docs and trying a few things I was only able to delete all versions for a corresponding ticker. In my use case, I upload data as new version but I would like to keep for example the last 6 versions. So far I either only keep the last 1-2 with prune=True or I keep all the version with prune = False, both are not ideal for me.

Thanks for your help in advance and thank you so much for creating this awesome tool. 

Tom

**Comment by shashank88** [comment]
There is a ._delete_version method in the library that you can use for this: https://github.com/man-group/arctic/blob/master/arctic/store/version_store.py#L901

**Comment by shashank88** [comment]
It's hidden intentionally though as iirc it had some issues when you were appending which deduped blocks and then ended up deleting the base version. It should be fine if you are not.

**Comment by tomnewg** [comment]
awesome thanks @shashank88. I will test this.
