### ISSUE TITLE
Pandas upgrade required

### ISSUE THREAD

**Issue by t1user** [man-group/arctic#868]
#### Arctic Version

```
# Arctic version here
```
1.79.4

#### Arctic Store

```
# VersionStore, TickStore, or ChunkStore
```
VersionStore

#### Platform and version

Ubuntu 20.04

#### Description of problem and/or code sample that reproduces the issue

Dear Arctic Team, would you consider upgrading pandas? I keep getting warnings about Panel being deprecated and it's annoying... Would really appreciate it.

**Comment by bmoscon** [comment]
They're just warnings, they dont prevent you from using the latest version of pandas

**Comment by t1user** [comment]
Yeah, I know. But still... 😁

**Comment by EklipZgit** [comment]
seems a bit important to update this if Panel is going to be removed completely in the next version of pandas :)
```
...\lib\site-packages\arctic\_util.py:6: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal
...\lib\site-packages\arctic\store\_pandas_ndarray_store.py:6: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import DataFrame, Series, Panel
```
**The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version**

Is there a significant amount of work that would need to go into upgrading?

**Comment by camizulub** [comment]
@EklipZgit The util warning is very ease to silence, just modify the code from pandas.testing import assert_frame_equal

The Pandas Panel requires more work, since the data requires some structure. I hope the collaborators can give us some insight in how to solve it.

**Comment by dbrakenhoff** [comment]
pandas.Panel has been deprecated since pandas version 0.20. Perhaps the Panel import can be wrapped in a try/except? And then add a message on import failure that if you want to use Panel you need pandas version 1.1 or lower? It should work fine for pandas v1.2 then (except of course if you want to actually do anything with Panels).

It would be nice to be able to use the latest pandas with arctic! Thanks for all the great work by the way!

**Comment by shashank88** [comment]
Closing this as Panel is now inside a try / except block.

**Comment by t1user** [comment]
Sorry for drilling on that, but is there a new version that incorporates
the try / except block? When I try to update from pip, it doesn't seem to
work, the latest version is still 1.79.4, which I installed a couple months
ago. And it screams the deprecation warning for pandas panel.
