### ISSUE TITLE
Garbage collection for VersionStore

### ISSUE THREAD

**Issue by qiuwei** [man-group/arctic#869]
#### Arctic Version
1.79.3

#### Arctic Store

VesionStore

#### Platform and version
Ubuntu 18.04

#### Description of problem and/or code sample that reproduces the issue
I was writing a huge DataFrame(about 40Gigabytes) into a version store. For some reason, the writing process crashed. The symbol does not show up in library.list_symbols().
However, disk space is still used. How can I clean up the partially written data?

**Comment by apoorva-saxena** [comment]
I think fsck should be able to catch this if not there are 2 things you can do:
a) If the lib had just one symbol you can delete the library which would, in turn, delete the collections which have the leaked data chunks
b) Go to mongo and run a delete query for that symbol as regex

**Comment by shashank88** [comment]
I think fsck should be able to catch this if not there are 2 things you can do:
a) If the lib had just one symbol you can delete the library which would, in turn, delete the collections which have the leaked data chunks
b) Go to mongo and run a delete query for that symbol as regex

**Comment by qiuwei** [comment]
Thanks for the tips!
