### ISSUE TITLE
What's the recommended way to clean up connections when program completes?

### ISSUE THREAD

**Issue by at-cf** [man-group/arctic#870]
I have a system that uses Arctic and my workers get spawned frequently/randomly, if they open connections to Mongo through Arctic, how should I clean them up properly? `arctic.reset()`? I don't want to exhaust Mongo's connection pool and depend on timeout to clean up, that's poor practice.

**Comment by shashank88** [comment]
.reset() should close all connections, are you seeing leakage after running it?

**Comment by at-cf** [comment]
No sir, for some reason I was seeing reconnect and thought reset() might be intended to reconnect, but this was my mistake. Thank you.
