### ISSUE TITLE
ValueError: unsupported pickle protocol: 5

### ISSUE THREAD

**Issue by tomnewg** [man-group/arctic#874]
Hi guys,

First things first arctic is one of the best tools out there. Thank you so much for this. It all works perfectly. However, I recently updated to python 3.8 and uploaded a lot of dataframes into mongodb with arctic. On other machines I still run 3.7 and are not able to upgrade as these are installed on a server. When downloading dataframes with verison 3.7 I get the following error:
"ValueError: unsupported pickle protocol: 5"
Python 3.8 uses pickle5. I tried to install pickle5 on the 3.7 machine but got an error. Is there any workaround to still download the dataframes with python 3.7 when they were uploaded with python 3.8?

Many thanks for your help

Tom

**Comment by shashank88** [comment]
Ahh, you are probably the first user of python 3.8 with this :) . I will update my python and see if there are any other issues that we need to handle with py3.8 . Will fix supporting pickle5

**Comment by tomnewg** [comment]
thanks @shashank88. Just to reiterate. Everything is working perfectly fine with python3.8 and arctic. The issue is only when downloading 3.8-uploaded dataframes with 3.7

**Comment by rladeira** [comment]
Is arctic already tested for python 3.7? Is it safe to use it with this python version?

**Comment by shashank88** [comment]
https://github.com/man-group/arctic/pull/892/commits/16023ed061e4ff0ec176da8a3f3073f23d252029 should fix this
