### ISSUE TITLE
Qn: Best practices for storing multiple levels of data granularity for one symbol

### ISSUE THREAD

**Issue by luongjames8** [man-group/arctic#876]
Can anyone share some best practices for storing multiple levels of data granularity for one symbol? 

For example, say my primary reference data is of daily frequency, but for some symbols I also have minute data (but it may not be for the entire span of the daily data). 

Do I need separate symbols for daily/intraday in version store? Is there a better way to do this?

**Comment by shashank88** [comment]
Yeah, I would suggest storing data of different granularity in separate symbols (or even different libraries) given it doesn't make much sense to read out the minute bar granularity when you care about the daily data.
Closing this for now, please reopen if you have more questions.
