### ISSUE TITLE
Panel not available in pandas 1.2

### ISSUE THREAD

**Issue by rgrit91** [man-group/arctic#884]
Starting from pandas 1.2 Panel is not available anymore, so this causes an error:

arctic/store/_pandas_ndarray_store.py", line 6, in <module>
    from pandas import DataFrame, Series, Panel
ImportError: cannot import name 'Panel' from 'pandas'

**Comment by ahmadazizi** [comment]
yes, Panel has been removed in recent stable versions of Pandas. Installation will interrupt

**Comment by shashank88** [comment]
I guess this will be a blocker for people to be on the latest pandas version, we could handle the import error here. WIll take a look over the weekend

**Comment by shashank88** [comment]
I just realized this is already merged in by @enricodetoma https://github.com/man-group/arctic/pull/881

**Comment by enricodetoma** [comment]
Please also take a look at pull request #887 (not yet merged) which contains an additional fix
