### ISSUE TITLE
would a lot null value occupy disk space in column-based chunkstore?

### ISSUE THREAD

**Issue by Haoxing** [man-group/arctic#890]
Hi,

I really like the project. I understand that the chunkstore is column-based to raise the read/compress efficiency. 

my concern is: if there is one column has 90% null + only 10% real data, compare with the column filled with 100% real data, does that mean this column only occupy about 10% disk space than the second case suppose data type is the same?   More general speaking, would the null value be filled with a fixed size (and how big?) placeholders on arctic level in chunkstore?  

Thanks a lot,

**Comment by shashank88** [comment]
From what I remember, chunkstore uses the same serializer as version store which uses LZ4 for compression: https://github.com/man-group/arctic/blob/master/arctic/_compression.py

So the space occupied on disk would depend on how well LZ4 compresses chunks of NaNs which it seems to do quite well based on some experiments I did last year (obviously depending on how the data is interleaved with NaNs).

TickStore does handle sparseness much better so if you are only working with sparse tick data, you can take a look at that as well. 
 
Hope this answers your question. Closing this, for now, feel free to reopen if you have more questions.
