### ISSUE TITLE
Fix failing builds: https://travis-ci.org/github/man-group/arctic/jobs/762598165

### ISSUE THREAD

**Issue by shashank88** [man-group/arctic#893]
On a quick glance, some failing tests seem to be returning None, both VersionStore and ChunkStore. Need to take a proper look at this, as it's blocking quite a few PRs

**Comment by bmoscon** [comment]
https://github.com/man-group/arctic/pull/883 <- this PR starts to resolve a lot of the current issues

**Comment by shashank88** [comment]
I think I missed this PR. Seems to be dead atm, do you know what caused so many tests to suddenly start failing? Is this a Python 3.7 thing or some recent change?

**Comment by bmoscon** [comment]
Same thing is always is: pandas released a new version
