### ISSUE TITLE
Setting up Arctic and TickStore with Redis

### ISSUE THREAD

**Issue by ramy-sharif** [man-group/arctic#894]
#### Arctic Version

```
V1.79.4
```

#### Arctic Store

```
TickStore
```

#### Platform and version
```
Ubuntu, AWS
```
#### Description of problem and/or code sample that reproduces the issue

It's a bit unclear to me how to setup custom storage engines, the documentation is missing that part. I'm looking to setup TickStore with Redis so my question is, how do I setup a `connection = Arctic()` such that it uses Redis as storage engine as opposed to MongoDB?

Thanks.

**Comment by shashank88** [comment]
You can't do that atm, the TickStore architecture is strongly tied to Mongo. You could look at all the Mongo calls being made in TickStore and try adding a redis store with an equivalent of those operations, but it might be a bit tricky. Closing this, feel free to reopen if you have more questions.
