### ISSUE TITLE
Missing pip package 1.80.0

### ISSUE THREAD

**Issue by calpa** [man-group/arctic#896]
The latest release is 1.80.0, but not in pip.
One may use `git+https://github.com/manahl/arctic.git` instead of `arctic==1.80.0` in requirements.txt to workaround this issue.

## How to reproduce?
```
pip3 install arctic==1.80.0
```
Problem:
```
ERROR: Could not find a version that satisfies the requirement arctic==1.80.0
ERROR: No matching distribution found for arctic==1.80.0
```

Workaround:
```
pip3 install git+https://github.com/manahl/arctic.git
```

I wonder whether this project is still maintained...

**Comment by shashank88** [comment]
Hi @calpa we will take a look

**Comment by shashank88** [comment]
How did you get:  1.18.0 ?

**Comment by calpa** [comment]
Use `pip3 install git+https://github.com/manahl/arctic.git` instead of `pip3 install arctic==1.80.0` as the 1.80.0 is not released in pip.

**Comment by calpa** [comment]
@shashank88 can you release 1.80.0 to pip?

**Comment by shashank88** [comment]
@bmoscon was 1.80 the last one we released or updated in the docs?

**Comment by bmoscon** [comment]
@shashank88 1.80.0 will be the next release. Its the version in master in github. Once thats released the version in github will bump to 1.80.1

**Comment by bmoscon** [comment]
@calpa its not missing, it hasnt been released yet

**Comment by calpa** [comment]
@bmoscon I am looking forward to use the latest version of arctic, please help.

**Comment by bmoscon** [comment]
wait for it to be released to pypi or use the code in github, nothing else that anyone can do
