### ISSUE TITLE
Chunck store read is very slow

### ISSUE THREAD

**Issue by Harishangaran** [man-group/arctic#900]
#### Arctic Version
```
# 1.80
```

#### Arctic Store

```
# ChunkStore
```

**Comment by shashank88** [comment]
@Harishangaran can you put the repro steps here? 77s seems way off.

**Comment by Harishangaran** [comment]
Hi Shashank,

The pandas version is 1.0.3

##########################################
from connect.mongoConnect import *
from timerUtil.timer import Timer

store = Arctic(client)

library = store['test']

######## READ PRICES ####################
t = Timer()
t.start()
item = library.read('GOOG')
t.stop()

print(item)

**Comment by Harishangaran** [comment]
Sample data

Index               Close
2004-09-02	49.4098014831543
2004-08-19	49.813289642333984
2004-09-08	50.181907653808594
2004-09-03	50.28651428222656
2004-08-20	50.316402435302734
2004-09-07	50.316402435302734

**Comment by Harishangaran** [comment]
Any idea why it could be?

**Comment by bmoscon** [comment]
its either your version of pandas or its been recently fixed by the PR that @TomTaylorLondon merged in
