### ISSUE TITLE
Naming database other than "arctic"

### ISSUE THREAD

**Issue by bmicognito** [man-group/arctic#915]
#### Arctic Version

```
# 1.79.4
```

#### Arctic Store

```
# VersionStore
```

#### Platform and version

Windows 10 x64

#### Description of problem and/or code sample that reproduces the issue

The database name cannot be named with another name than "arctic". I see the name is coded in arctic.py line 68 as "DB_PREFIX = "arctic". It would be interesting to name it differently by sending a name as an argument of class Arctic(). 
Sorry if it's already the case. I played around with the code and went through all of the docs and it didn't seem to be possible at this point.

**Comment by jasonlocal** [comment]
@bmicognito Thanks for raising this issue. I can look into this. Would you mind posting a code snippet, and show the current behavior and expected behavior ? That would server as a good vetting evidence once we make the code modification

**Comment by jasonlocal** [comment]
legacy issue - cleaning up this ticket for now. Please feel free to reopen if this is still an issue
