### ISSUE TITLE
Docs have broken links

### ISSUE THREAD

**Issue by vietlq** [man-group/arctic#956]
## Docs have broken links

Follow the link: https://arctic.readthedocs.io/en/latest/

### Video

    * [2015 All Your Base : Building a time series database: 10^12 rows and counting](https://vimeo.com/album/3660528/video/145842301) => Private
    * [2014 PyData : Python and MongoDB as a Platform for Financial Market Data](https://www.youtube.com/watch?v=FVyIxdxsyok) => OK
    * [2014 MongoDB World : Replacing Traditional Technologies with MongoDB: A Single Platform for All Financial Data at AHL](https://www.mongodb.com/presentations/replacing-traditional-technologies-mongodb-single-platform-all-financial-data-ahl) => Nothing!

### Slides

    * [2015 All Your Base : Building a time series database: 10^12 rows and counting](http://www.slideshare.net/JamesBlackburn1/building-a-time-series-database?ref=http://lanyrd.com/2015/all-your-base/sdrydc/) => Content removed
    * [2015 PyData : Arctic: High-performance IoT and financial data storage with Python and MongoDB](http://www.slideshare.net/JamesBlackburn1/2015-pydata-highperformance-iot-and-financial-data-storage-with-python-and-mongodb) => Content removed
    * [2014 PyData : Python and MongoDB as a Platform for Financial Market Data](http://www.slideshare.net/JamesBlackburn1/mongodb-and-python-as-a-market-data-platform) => Content removed
    * [2014 MongoDB World : Replacing Traditional Technologies with MongoDB: A Single Platform for All Financial Data at AHL](http://www.slideshare.net/mongodb/replacing-traditional-technologies-with-mongodb-a-single-platform-for-all-financial-data-at-ahl?ref=https://www.mongodb.com/presentations/replacing-traditional-technologies-mongodb-single-platform-all-financial-data-ahl) => OK

**Comment by dunckerr** [comment]
@vietlq - looks like the videos are on platforms that have gone out of business or setup a pay-wall.  We should get the originals and put them on youtube or put them on a man server.
