### ISSUE TITLE
most recent version not pip installing on mac M1

### ISSUE THREAD

**Issue by stupidanon** [man-group/arctic#968]
#### Arctic Version

works with `pip install arctic==1.79.3`
does not work with `pip install arctic`

#### Platform and version

Mac M1
Python 3.10 Intel 64

#### Description of problem and/or code sample that reproduces the issue

Attempted installation gives this error: 
_NOTE: ERROR WAS TOO BIG TO COPY ALL OF IT_

```
...

                ^
            numpy/core/src/umath/cpuid.c:38:5: warning: unused function 'os_avx512_support' [-Wunused-function]
            int os_avx512_support(void)
                ^
            numpy/core/src/umath/cpuid.c:52:5: warning: unused function 'cpu_supports_fma' [-Wunused-function]
            int cpu_supports_fma(void)
                ^
            3 warnings generated.
            numpy/core/src/umath/cpuid.c:21:5: warning: unused function 'os_avx_support' [-Wunused-function]
            int os_avx_support(void)
                ^
            numpy/core/src/umath/cpuid.c:38:5: warning: unused function 'os_avx512_support' [-Wunused-function]
            int os_avx512_support(void)
                ^
            numpy/core/src/umath/cpuid.c:52:5: warning: unused function 'cpu_supports_fma' [-Wunused-function]
            int cpu_supports_fma(void)
                ^
            3 warnings generated.
            clang: /private/var/folders/g5/5wshf1355p74787_h5l23s4m0000gn/T/pip-wheel-vdqmfyvs/numpy_4359a0222b254a37b19f79e7d715df1c/numpy/_build_utils/src/apple_sgemv_fix.c
            clang: numpy/core/src/common/cblasfuncs.c
            In file included from /private/var/folders/g5/5wshf1355p74787_h5l23s4m0000gn/T/pip-wheel-vdqmfyvs/numpy_4359a0222b254a37b19f79e7d715df1c/numpy/_build_utils/src/apple_sgemv_fix.c:26:
            In file included from numpy/core/include/numpy/arrayobject.h:4:
            In file included from numpy/core/include/numpy/ndarrayobject.h:21:
            build/src.macosx-10.9-universal2-3.10/numpy/core/include/numpy/__multiarray_api.h:1463:1: warning: unused function '_import_array' [-Wunused-function]
            _import_array(void)
            ^
            1 warning generated.
            In file included from /private/var/folders/g5/5wshf1355p74787_h5l23s4m0000gn/T/pip-wheel-vdqmfyvs/numpy_4359a0222b254a37b19f79e7d715df1c/numpy/_build_utils/src/apple_sgemv_fix.c:26:
            In file included from numpy/core/include/numpy/arrayobject.h:4:
            In file included from numpy/core/include/numpy/ndarrayobject.h:21:
            build/src.macosx-10.9-universal2-3.10/numpy/core/include/numpy/__multiarray_api.h:1463:1: warning: unused function '_import_array' [-Wunused-function]
            _import_array(void)
            ^
            1 warning generated.
            clang: numpy/core/src/common/python_xerbla.c
            clang: numpy/core/src/umath/ufunc_type_resolution.c
            clang: numpy/core/src/umath/override.c
            clang: numpy/core/src/multiarray/mapping.c
            4 warnings generated.
            clang: numpy/core/src/multiarray/methods.c
            4 warnings generated.
            numpy/core/src/umath/loops.c.src:363:18: warning: 'PyEval_CallObjectWithKeywords' is deprecated [-Wdeprecated-declarations]
                    result = PyEval_CallObject(tocall, arglist);
                             ^
            /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/ceval.h:24:5: note: expanded from macro 'PyEval_CallObject'
                PyEval_CallObjectWithKeywords(callable, arg, (PyObject *)NULL)
                ^
            /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/ceval.h:17:1: note: 'PyEval_CallObjectWithKeywords' has been explicitly marked deprecated here
            Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
            ^
            /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/pyport.h:513:54: note: expanded from macro 'Py_DEPRECATED'
            #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                                 ^
            numpy/core/src/umath/loops.c.src:2567:22: warning: code will never be executed [-Wunreachable-code]
                    npy_intp n = dimensions[0];
                                 ^~~~~~~~~~
            numpy/core/src/umath/loops.c.src:2566:29: note: silence by adding parentheses to mark code as explicitly dead
                if (IS_BINARY_REDUCE && 0) {
                                        ^
                                        /* DISABLES CODE */ ( )
            numpy/core/src/umath/loops.c.src:2567:22: warning: code will never be executed [-Wunreachable-code]
                    npy_intp n = dimensions[0];
                                 ^~~~~~~~~~
            numpy/core/src/umath/loops.c.src:2566:29: note: silence by adding parentheses to mark code as explicitly dead
                if (IS_BINARY_REDUCE && 0) {
                                        ^
                                        /* DISABLES CODE */ ( )
            numpy/core/src/umath/loops.c.src:2567:22: warning: code will never be executed [-Wunreachable-code]
                    npy_intp n = dimensions[0];
                                 ^~~~~~~~~~
            numpy/core/src/umath/loops.c.src:2566:29: note: silence by adding parentheses to mark code as explicitly dead
                if (IS_BINARY_REDUCE && 0) {
                                        ^
                                        /* DISABLES CODE */ ( )
            4 warnings generated.
            clang: build/src.macosx-10.9-universal2-3.10/numpy/core/src/umath/matmul.c
            clang: build/src.macosx-10.9-universal2-3.10/numpy/core/src/umath/clip.c
            error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DNO_ATLAS_INFO=3 -DHAVE_CBLAS -Ibuild/src.macosx-10.9-universal2-3.10/numpy/core/src/umath -Ibuild/src.macosx-10.9-universal2-3.10/numpy/core/src/npymath -Ibuild/src.macosx-10.9-universal2-3.10/numpy/core/src/common -Inumpy/core/include -Ibuild/src.macosx-10.9-universal2-3.10/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -Ibuild/src.macosx-10.9-universal2-3.10/numpy/core/src/common -Ibuild/src.macosx-10.9-universal2-3.10/numpy/core/src/npymath -c build/src.macosx-10.9-universal2-3.10/numpy/core/src/multiarray/scalartypes.c -o build/temp.macosx-10.9-universal2-cpython-310/build/src.macosx-10.9-universal2-3.10/numpy/core/src/multiarray/scalartypes.o -MMD -MF build/temp.macosx-10.9-universal2-cpython-310/build/src.macosx-10.9-universal2-3.10/numpy/core/src/multiarray/scalartypes.o.d -msse3 -I/System/Library/Frameworks/vecLib.framework/Headers" failed with exit status 1
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      ERROR: Failed to build one or more wheels
      Traceback (most recent call last):
        File "/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/lib/python3.10/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/bin/python3.10-intel64', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/g5/5wshf1355p74787_h5l23s4m0000gn/T/tmpub7go7on', '--quiet', 'numpy<1.19.0']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/g5/5wshf1355p74787_h5l23s4m0000gn/T/pip-install-tdivf5mi/arctic_e1f8471277ac469aa5cdb07c4a328ace/setup.py", line 59, in <module>
          setup(
        File "/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/lib/python3.10/site-packages/setuptools/dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/lib/python3.10/site-packages/setuptools/dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/lib/python3.10/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/bin/python3.10-intel64', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/g5/5wshf1355p74787_h5l23s4m0000gn/T/tmpub7go7on', '--quiet', 'numpy<1.19.0']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by dunckerr** [comment]
Hi -it’s almost certainly the python version which is the problem - we currently only support (and have tested) up to 3.8.
Thanks
Duncan

On 29 Oct 2022, at 14:02, stupidanon ***@***.***> wrote:

﻿

Arctic Version

works with pip install arctic==1.79.3
does not work with pip install arctic

Platform and version

Mac M1
Python 3.10 Intel 64

Description of problem and/or code sample that reproduces the issue

Attempted installation gives this error:
NOTE: ERROR WAS TOO BIG TO COPY ALL OF IT

...

                ^
            numpy/core/src/umath/cpuid.c:38:5: warning: unused function 'os_avx512_support' [-Wunused-function]
            int os_avx512_support(void)
                ^
            numpy/core/src/umath/cpuid.c:52:5: warning: unused function 'cpu_supports_fma' [-Wunused-function]
            int cpu_supports_fma(void)
                ^
            3 warnings generated.
            numpy/core/src/umath/cpuid.c:21:5: warning: unused function 'os_avx_support' [-Wunused-function]
            int os_avx_support(void)
                ^
            numpy/core/src/umath/cpuid.c:38:5: warning: unused function 'os_avx512_support' [-Wunused-function]
            int os_avx512_support(void)
                ^
            numpy/core/src/umath/cpuid.c:52:5: warning: unused function 'cpu_supports_fma' [-Wunused-function]
            int cpu_supports_fma(void)
                ^
            3 warnings generated.
            clang: /private/var/folders/g5/5wshf1355p74787_h5l23s4m0000gn/T/pip-wheel-vdqmfyvs/numpy_4359a0222b254a37b19f79e7d715df1c/numpy/_build_utils/src/apple_sgemv_fix.c
            clang: numpy/core/src/common/cblasfuncs.c
            In file included from /private/var/folders/g5/5wshf1355p74787_h5l23s4m0000gn/T/pip-wheel-vdqmfyvs/numpy_4359a0222b254a37b19f79e7d715df1c/numpy/_build_utils/src/apple_sgemv_fix.c:26:
            In file included from numpy/core/include/numpy/arrayobject.h:4:
            In file included from numpy/core/include/numpy/ndarrayobject.h:21:
            build/src.macosx-10.9-universal2-3.10/numpy/core/include/numpy/__multiarray_api.h:1463:1: warning: unused function '_import_array' [-Wunused-function]
            _import_array(void)
            ^
            1 warning generated.
            In file included from /private/var/folders/g5/5wshf1355p74787_h5l23s4m0000gn/T/pip-wheel-vdqmfyvs/numpy_4359a0222b254a37b19f79e7d715df1c/numpy/_build_utils/src/apple_sgemv_fix.c:26:
            In file included from numpy/core/include/numpy/arrayobject.h:4:
            In file included from numpy/core/include/numpy/ndarrayobject.h:21:
            build/src.macosx-10.9-universal2-3.10/numpy/core/include/numpy/__multiarray_api.h:1463:1: warning: unused function '_import_array' [-Wunused-function]
            _import_array(void)
            ^
            1 warning generated.
            clang: numpy/core/src/common/python_xerbla.c
            clang: numpy/core/src/umath/ufunc_type_resolution.c
            clang: numpy/core/src/umath/override.c
            clang: numpy/core/src/multiarray/mapping.c
            4 warnings generated.
            clang: numpy/core/src/multiarray/methods.c
            4 warnings generated.
            numpy/core/src/umath/loops.c.src:363:18: warning: 'PyEval_CallObjectWithKeywords' is deprecated [-Wdeprecated-declarations]
                    result = PyEval_CallObject(tocall, arglist);
                             ^
            /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/ceval.h:24:5: note: expanded from macro 'PyEval_CallObject'
                PyEval_CallObjectWithKeywords(callable, arg, (PyObject *)NULL)
                ^
            /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/ceval.h:17:1: note: 'PyEval_CallObjectWithKeywords' has been explicitly marked deprecated here
            Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
            ^
            /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/pyport.h:513:54: note: expanded from macro 'Py_DEPRECATED'
            #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                                 ^
            numpy/core/src/umath/loops.c.src:2567:22: warning: code will never be executed [-Wunreachable-code]
                    npy_intp n = dimensions[0];
                                 ^~~~~~~~~~
            numpy/core/src/umath/loops.c.src:2566:29: note: silence by adding parentheses to mark code as explicitly dead
                if (IS_BINARY_REDUCE && 0) {
                                        ^
                                        /* DISABLES CODE */ ( )
            numpy/core/src/umath/loops.c.src:2567:22: warning: code will never be executed [-Wunreachable-code]
                    npy_intp n = dimensions[0];
                                 ^~~~~~~~~~
            numpy/core/src/umath/loops.c.src:2566:29: note: silence by adding parentheses to mark code as explicitly dead
                if (IS_BINARY_REDUCE && 0) {
                                        ^
                                        /* DISABLES CODE */ ( )
            numpy/core/src/umath/loops.c.src:2567:22: warning: code will never be executed [-Wunreachable-code]
                    npy_intp n = dimensions[0];
                                 ^~~~~~~~~~
            numpy/core/src/umath/loops.c.src:2566:29: note: silence by adding parentheses to mark code as explicitly dead
                if (IS_BINARY_REDUCE && 0) {
                                        ^
                                        /* DISABLES CODE */ ( )
            4 warnings generated.
            clang: build/src.macosx-10.9-universal2-3.10/numpy/core/src/umath/matmul.c
            clang: build/src.macosx-10.9-universal2-3.10/numpy/core/src/umath/clip.c
            error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DNO_ATLAS_INFO=3 -DHAVE_CBLAS -Ibuild/src.macosx-10.9-universal2-3.10/numpy/core/src/umath -Ibuild/src.macosx-10.9-universal2-3.10/numpy/core/src/npymath -Ibuild/src.macosx-10.9-universal2-3.10/numpy/core/src/common -Inumpy/core/include -Ibuild/src.macosx-10.9-universal2-3.10/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -Ibuild/src.macosx-10.9-universal2-3.10/numpy/core/src/common -Ibuild/src.macosx-10.9-universal2-3.10/numpy/core/src/npymath -c build/src.macosx-10.9-universal2-3.10/numpy/core/src/multiarray/scalartypes.c -o build/temp.macosx-10.9-universal2-cpython-310/build/src.macosx-10.9-universal2-3.10/numpy/core/src/multiarray/scalartypes.o -MMD -MF build/temp.macosx-10.9-universal2-cpython-310/build/src.macosx-10.9-universal2-3.10/numpy/core/src/multiarray/scalartypes.o.d -msse3 -I/System/Library/Frameworks/vecLib.framework/Headers" failed with exit status 1
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      ERROR: Failed to build one or more wheels
      Traceback (most recent call last):
        File "/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/lib/python3.10/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/bin/python3.10-intel64', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/g5/5wshf1355p74787_h5l23s4m0000gn/T/tmpub7go7on', '--quiet', 'numpy<1.19.0']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/g5/5wshf1355p74787_h5l23s4m0000gn/T/pip-install-tdivf5mi/arctic_e1f8471277ac469aa5cdb07c4a328ace/setup.py", line 59, in <module>
          setup(
        File "/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/lib/python3.10/site-packages/setuptools/dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/lib/python3.10/site-packages/setuptools/dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/lib/python3.10/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/Users/samson11/sandbox/crypto-analytics/crypto-analytics_venv/bin/python3.10-intel64', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/g5/5wshf1355p74787_h5l23s4m0000gn/T/tmpub7go7on', '--quiet', 'numpy<1.19.0']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by bug-or-feature** [comment]
@stupidanon I saw a similar issue trying to install numpy on a new Apple with M1 Max chip. Its not about the python version, its something to do with a low level Maths library that numpy depends on called [OpenBLAS](https://github.com/xianyi/OpenBLAS). I can't pretend to understand it completely, but the solution for me was to install Cython and numpy directly with commands like:

```
OPENBLAS="$(brew --prefix openblas)" MACOSX_DEPLOYMENT_TARGET=12.6 python3 -m pip install cython --no-use-pep517
OPENBLAS="$(brew --prefix openblas)" MACOSX_DEPLOYMENT_TARGET=12.6 python3 -m pip install numpy --no-use-pep517
```

You may need to specify a version of numpy that matches the needs of Arctic and/or pandas

**Comment by stupidanon** [comment]
@bug-or-feature yes this is what I did, forgot to link it, thank you👍
