### ISSUE TITLE
MongoDB 4.2 EOL April 2023 - What's Next?

### ISSUE THREAD

**Issue by luongjames8** [man-group/arctic#970]
I recently received a email from MongoDB reminding that my 4.2 cluster will be reaching EOL in April 2023. I am sure I am not the only one who received this...

@jamesblackburn -What's the plan here?  Will we need to request an extension from Mongo to continue running 4.2? Is there any roadmap to when if at all you will support 4.4 or 5.0?  Per #938 a 4.4 or 5.0 version doesn't seem to be close?

Will we need to plan to move to the S3 version? What's going on here? 

Some clarity here would help... as the date is approaching real fast.

Btw - Thanks for the v1.80.5

**Comment by luongjames8** [comment]
@bmoscon any one else can shed some light here?

**Comment by dunckerr** [comment]
Hi there we are currently testing against Mongo 4.2.22 and plan to upgrade thru 4.x to 5.x as quickly as we can.
If you are interested in a S3 backend with the same arctic API have you seen our new project: https://www.man.com/arcticdb
Thanks
Duncan

On 4 Nov 2022, at 01:37, luongjames8 ***@***.***> wrote:

﻿

@bmoscon<https://github.com/bmoscon> any one else can shed some light here?

**Comment by bug-or-feature** [comment]
> If you are interested in a S3 backend with the same arctic API have you seen our new project: https://www.man.com/arcticdb

Front page of that URL should say:

Easy install: pip install **arcticdb**

**Comment by dunckerr** [comment]
Thanks

On 5 Nov 2022, at 13:13, Andy Geach ***@***.***> wrote:

﻿

If you are interested in a S3 backend with the same arctic API have you seen our new project: https://www.man.com/arcticdb

Front page of that URL should say:

Easy install: pip install arcticdb

**Comment by qianyun210603** [comment]
@dunckerr 

Seeing that in the link you provided [](https://www.man.com/arcticdb) it actually says `pip install arctic` for installing S3 backend, no `db` at end.
So currently which version does `pip install arctic` install? MongoDB version or S3 version?

Also is there any documentation on how to configure the S3 version? How will be S3 version be provided? will it be open-source?

Thanks a lot!

**Comment by dunckerr** [comment]
@luongjames8 The tests are all passing with mongo 4.4.18   I haven't done a release yet, but the changes are merged into master.  Hope that helps. 
Duncan

**Comment by luongjames8** [comment]
Brilliant. Thanks for the update, @dunckerr!
