### ISSUE TITLE
arctic.exceptions.QuotaExceededException: Mongo Quota Exceeded: xxx 10.366 / 10 GB used

### ISSUE THREAD

**Issue by Tianxu-Jia** [man-group/arctic#973]
# VersionStore
#### Description of problem and/or code sample that reproduces the issue
I am using VersionStore. 

My error:
arctic.exceptions.QuotaExceededException: Mongo Quota Exceeded: arctic.xxx 10.366 / 10 GB used

Could you please tell me how to set more quota than 10G?

Many thanks

**Comment by bmoscon** [comment]
https://github.com/man-group/arctic/issues/79
