### ISSUE TITLE
best practice usage

### ISSUE THREAD

**Issue by RockScience** [man-group/arctic#975]
Hello, thank you very much for making this open source

1/ is there a optimised way to access timeseries of revisions. In the VersionStore if we have saved several versions

**version1 saved at 2022-01-04**
2022-01-01   1
2022-01-02   2

**version2 saved at 2022-01-05**
2022-01-01   1
2022-01-02   3

then I would like to retrieve in an efficient manner the timeseries of change for the value as of  2022-01-02, ie:
2022-01-04  2
2022-01-05  3

2/ is there a permission layer allowing to choose who has access to which ticker?

**Comment by dunckerr** [comment]
Q1.  have a look at https://github.com/man-group/arctic/blob/master/docs/versionstore.md
Q2.  no.  We have a credentials system which sits on top of arctic.
