### ISSUE TITLE
argument of type 'NoneType' is not iterable (when updating)

### ISSUE THREAD

**Issue by TwoBeng** [man-group/arctic#977]
#### Arctic Version

```
1.80.5
```

#### Arctic Store

```
 ChunkStore
```

#### Platform and version

Linux

#### Description of problem and/or code sample that reproduces the issue
I also encountered the same bug. When the original collection has this row of data, but the metadata collection does not have this row of data, this bug will occur when updating
https://github.com/man-group/arctic/issues/923#issue-1046762464

**Comment by dunckerr** [comment]
If you have a code fragment to repeat the issues, please re-open & I'll investigate.
